services:
  web:
    name: lol-draft
    image: hl-docker-registry.g3tech.net/lol-draft:latest
    ports:
      - 1006:80
    environment:
      - DATABASE_URL=sqlite://./lol-draft.db?mode=rwc
    volumes:
      - ${APP_BASE}/lol-draft.db:/app/lol-draft.db